stages:
  - generate

generate:
  stage: generate
  variables:
      DOCKER_HOST: tcp://dockerdaemon:2375/
      DOCKER_DRIVER: overlay2
      DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:dind
      alias: dockerdaemon
  image:
    name: docker:stable
  before_script:
    - docker pull minlag/mermaid-cli
  script:
    - ./generate.sh
  artifacts:
    paths:
      - output/*
    untracked: true
