image: docker:19.03.13

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:19.03.13-dind

before_script:
  - docker info

build:
  stage: build
  before_script:
    - docker pull minlag/mermaid-cli
  script:
    - ./generate.sh
  artifacts:
    paths:
      - output/*
    untracked: true
