stages:
  - generate

variables:
  DOCKER_TLS_CERTDIR: "/certs"

image: docker:19.03.12

services:
  - docker:19.03.12-dind

generate:
  stage: generate
  before_script:
    - docker pull minlag/mermaid-cli
  script:
    - ./generate.sh
  artifacts:
    paths:
      - output/*
    untracked: true
