image: docker:19.03.12

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://localhost:2375

services:
  - docker:19.03.12-dind

before_script:
  - docker info

build:
  stage: build
  script:
    - docker pull minlag/mermaid-cli
    - ./generate.sh
  artifacts:
    paths:
      - output/*
    untracked: true
