stages:
  - generate

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

generate:
  stage: generate
  image: docker
  before_script:
    - docker pull minlag/mermaid-cli
  script:
    - ./generate.sh
  artifacts:
    paths:
      - output/*
    untracked: true
